# Generated by Django 4.2.1 on 2023-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=400)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('precisa_ser_feito', 'Precisa ser feito')], default='importante', max_length=25)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente'), ('adiado', 'Adiado'), ('em_andamento', 'Em andamento')], default='pendente', max_length=25)),
            ],
        ),
    ]
